server:
  port: 8080

spring:
  profiles:
    active: dev

eureka:
  server:
    enable-self-preservation: false
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    com.netflix.eureka: off
    com.netflix.discovery: off